services:
  - type: web
    name: sabif
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn tuto.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sabif-bd
          property: connectionString
    pythonVersion: 3.11
