# Generated by Django 5.2.6 on 2025-09-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0002_acceuilperso'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenus',
            name='lien',
            field=models.URLField(blank=True),
        ),
    ]
