# Generated by Django 5.2.6 on 2025-09-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0003_contenus_lien'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
