# Generated by Django 5.2.6 on 2025-09-09 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0004_contenus_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenus',
            name='image',
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('contenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='acceuil.contenus')),
            ],
        ),
    ]
