# Generated by Django 5.2.6 on 2025-09-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0005_remove_contenus_image_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceuilperso',
            name='disclaimer',
            field=models.TextField(blank=True),
        ),
    ]
