# Generated by Django 5.2.6 on 2025-09-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0006_acceuilperso_disclaimer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
