# Generated by Django 5.2.6 on 2025-09-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0007_visite'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenus',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
