# Generated by Django 5.2.6 on 2025-09-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0008_contenus_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenus',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
