# Generated by Django 5.2.6 on 2025-09-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0009_alter_contenus_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenus',
            name='num',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
